# -*- coding: utf-8 -*-
"""Langchain_Wikepedia_Retrievers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jdq40MRzKyMau22H6v5raoS2-XnWaQwZ
"""


"""# WikiPedia Retrievers"""

from langchain_community.retrievers import WikipediaRetriever

# Initialize the retriever (Optional: set language and top_k)
retriever = WikipediaRetriever(language="en", top_k_results=2)

# Define your query
query = "Give me some details about Louvre Museum?"

# Get the relevant Wikipedia documents
docs = retriever.invoke(query)

# Print retrieved content

for i, doc in enumerate(docs):
    print(f"Document {i+1}:")
    print(doc.page_content)
    print("\n")